### ISSUE TITLE
Sorting people

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#197]

**Comment by jasloe** [comment]
@cchristopherhowardd -- built out field and vocabulary for people called "Affiliation year". Goes back to 2010. Will build out front end view now. You can start populating the people nodes.

**Comment by cchristopherhowardd** [comment]
Date picker works great for Rome Prize Fellows. Can the Italian Fellows and Residents use the same drop-downs?

**Comment by cchristopherhowardd** [comment]
You can eliminate 2010 from the Affiliation Year field. The oldest People pages are the **2011** Fellows (at the Academy from 2010 to 2011).

**Comment by jasloe** [comment]
You bet. Get to it tomorrow.

**Comment by jasloe** [comment]
Oops, forgot to push this to dev! 

Have a look at residents and IF and test when you have a minute. I'm working on a quick module that restricts the select list to terms that are in the results. If I can't get that working today, I'll just hard code the terms into the select list. Hacky but it will work.

**Comment by jasloe** [comment]
@cchristopherhowardd -- Good/bad news: the restricted select filter is working well for our resources lists (e.g.: https://dev.aarome.org/research/resources/electronic-journals) but not so much for sorting people. The latter has a somewhat formidable aggregation which is difficult to work around and would require a refactor. 

I propose tabling this for now.  If/when the Directory project is resurrected, I'll take a closer look at implementing a more complete solution. 

Meantime, let me know which discipline terms you'd like exposed for IF and Residents.

**Comment by cchristopherhowardd** [comment]
I don't quite understand what the problem is. I am able to sort Italian Fellows and Residents by year and discipline using the date and discipline pickers, so I can't tell what's wrong on the surface.

Regarding disciplines, you can remove "Classical Studies & Archaeology" from the Rome Prize Fellows list, the Residents list (I changed Mary Beard from "CS&A" to "Ancient Studies"), and the Italian Fellows list.

In Residents, add "History of Art" and "History of Architecture" to the discipline picker. Remove "Modern Italian Studies" and "Renaissance and Early Modern Studies." Remove 2011 to 2014 in the year picker.

In Italian Fellows, remove "Modern Italian Studies" and add "Modern Studies." Remove 2011 to 2014 in the year picker.

**Comment by jasloe** [comment]
To clarify, the desired functionality is this:

_The select list is programmatically populated by terms that exist in the collection of nodes. If no nodes contain "Jewelry Design", then the item doesn't appear in the list._ 

It's a small thing but useful insofar that it is self-managing and requires no code or configuration intervention. Unfortunately, that functionality doesn't appear to be possible without writing another module. 

Instead, and as a workaround, I'm going to hard code the valid values in the select list. This means that every time you need to add a term, you'll have to contact me. 

Make sense?

I made those changes to the discipline/date pickers.

**Comment by cchristopherhowardd** [comment]
This situation makes sense now. 

Please add "Anthropology" to the Residents discipline picker.

**Comment by jasloe** [comment]
All set.
