### ISSUE TITLE
Deprecate some fields from Directory data model?

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#22]
A few of the fields in the directory data set contain long blocks of text (see below).

Do we want to migrate this data? To my untrained eye, much of it is a) of middling interest and b) terribly out of date. For example, publishing home and business addresses? 

The data feels like a snapshot in time and its usefulness has long passed. 

Thoughts?

#### Career and Employment
San Francisco Art Inst., Ceramics Dept., Head 1961-1965; UC, Berkeley, Prof. 1965-1992; NEA, Visual Arts Program, Dir. 1977-1981. Home Address: 6077 Ocean View Dr., Oakland, CA 94618

#### Memberships
Atlantic Coast Line Company, pres. 1894; served exec. Committee of Metropolitan Museum of Art, 1903 (second v.p., 1913); chmn. board of Safe Deposit and Trust Company, Baltimore, MDFellowships, Honors and Awards: Decorated Officer Legion of Honor (France)

#### Articles
"Le terme Deciane sull'Aventino," Archeologia Laziale 7 ( 1985): 139-144; "The Chalkotheke on the Athenian Acropolis," Hesperia 55 (1986): 75-87; selected inscriptions in Tituli 6, La collezione epigrafica dei musei capitolini: Inediti, revisioni, contributi al riordino, ed. Silvio Fanciera (Rome: Edizioni di Storia e Letteratura, 1987). 84-86, 329-330; with R. Wallace, "Latin seni crines and the Hair Style of Roman Brides," Selecta Classica 4 (1993): 43-48; "A Contribution of Andrea Palladio to the Study of Roman Thermae," JSAH 52 (1993): 189-198; "The Costume of the Roman Bride," in The World of Roman Costume, ed. L. Bonfante &amp; J. Sebesta (Madison: Univ. of Wisconsin Press, 1994), 54-64; The Baths of Trajan Decius on the Aventine, Roman Papers I, Journal of Roman Archaeology, supp. ser. 11 (1994): 1-88. Home Address: 18 Dana St., Amherst, MA 01002. Business Address: Art History Program, Univ. of Massachusetts, Amherst, MA 01003.

**Comment by jasloe** [comment]
More on the data model here: https://github.com/aarome/aarome/wiki/Migration-pattern-for-Directory-records

**Comment by cchristopherhowardd** [comment]
Keep the long blocks of text, if only because I do not know what the digital source of the information is. I do know its origins--a book called _The Centennial Directory of the American Academy in Rome_ that was published in 1995--but I don't know where the Word file (or whatever) used to generate the Directory information is.

If it’s possible to NOT import the home and business addresses, then don’t. That information is surely out of date.

The idea with importing the directory is to populate a page for every fellow, current and past, around which other webpages may relate. For instance, a page for a current fellow Michelle Berefeld (at http://aarome.org/people/michelleberenfeld) would be treated the same as the page for the unnamed fellow in the example you gave. Does that makes sense?

![img_0003](https://user-images.githubusercontent.com/38765846/41867585-80e09d2c-7881-11e8-9962-8eae45386678.jpg)
![img_0002](https://user-images.githubusercontent.com/38765846/41867586-80ee8234-7881-11e8-885e-8eb3960db36a.jpg)

**Comment by jasloe** [comment]
Yes, I took an OCR scan of the newer (2005?) edition of the book, converted it to a text file, and parsed it back in 2014. It was kind of a miserable job and I'm not too keen on digging back into it. Let's just pipe the text in and leave it be for now. We can always operate on the data at a later time.

**Comment by jasloe** [comment]
This portion of the project is postponed.
