### ISSUE TITLE
Migrate Society of Fellows News, Events, and Obituaries

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#222]
Content from the current site should be incorporated into the dev site. Everything from these pages:

https://www.aarome.org/people/alumni/sof/news
https://www.aarome.org/people/alumni/sof/events
https://www.aarome.org/people/alumni/sof/obituaries

Should appear here:

https://dev.aarome.org/society-of-fellows/news-events

In a section that functions like the News - Features section:

https://dev.aarome.org/news/features

**Comment by jasloe** [comment]
@cchristopherhowardd -- 

https://staging.aarome.org/society-of-fellows/news-events

Got part of this hashed out. 

There are a few issues, some technical, some not.

- Images not respecting image style rule (fixing this now)
- SOF NEWS vs SOF News. I think I can fix this with a database query. 
- There are no summaries for this content so no kicker below the image. Not sure what to do about this since there's no logical breakpoint for summaries (see last note).
- Fix inside page breadcrumb, e.g.: https://staging.aarome.org/society-of-fellows/news-events/sof-news-march-2018
- Can't comment too much on the nature of the writing but the formatting is sort of all over the place. 

Should be able to wrap this up tomorrow.

**Comment by jasloe** [comment]
Fixed styling.

**Comment by jasloe** [comment]
Change all caps to sentence case.

**Comment by cchristopherhowardd** [comment]
I can't do anything about the lack of summaries or the inconsistent writing and styling.

Can you remove the image caption from each item on the index page (https://staging.aarome.org/society-of-fellows/news-events)?

**Comment by jasloe** [comment]
Fixed.
