### ISSUE TITLE
Uniform height of People photos

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#283]
During the merge, we lost the uniform height of photos in the People section. Can you reinstate this?

Rome Prize Fellows:

<img width="1370" alt="Screen Shot 2020-04-09 at 3 43 14 PM" src="https://user-images.githubusercontent.com/38765846/78934617-3eb67d80-7a79-11ea-9f10-ae682af58c3b.png">

Residents:

<img width="1088" alt="Screen Shot 2020-04-09 at 3 44 39 PM" src="https://user-images.githubusercontent.com/38765846/78934648-4aa23f80-7a79-11ea-9404-60a2d738d5a1.png">

Italian Fellows

<img width="1245" alt="Screen Shot 2020-04-09 at 3 45 05 PM" src="https://user-images.githubusercontent.com/38765846/78934665-5130b700-7a79-11ea-82a4-8aadeb29bc05.png">

**Comment by jasloe** [comment]
That's intentional. Image sizes and aspect ratios are all over the place, some are very wide, some very high. On a site this size with so many variations, it's tough to find a happy medium. For example, compare Montalti with Zanellato. If we respect the ratio of Montalti, Zanellato will have text hanging off to the side and a gap on the right margin. Vice-versa, Montalti would be very tall and push all of the content out of the window (in the context of the slideshow) or into the next row (in the case of the people "grid"). (N.B.: The original design called for images with identical ratios.) 

However, I'm going to roll back to the old pattern and constrain the heights. We can find the edge cases (very wide images) and manually crop their widths to fit. Hope that makes sense.

**Comment by jasloe** [comment]
The photo attached to Marsha Ginsberg is an example of a too wide image.

**Comment by jasloe** [comment]
Ditto Samiya Bashir, Pamela Z.

**Comment by cchristopherhowardd** [comment]
I'll crop the extra-wide photos. The style we had on the staging site pre-merge, with constrained heights, looked just fine to me. That's what other staff members saw. Marques was concerned that Mark Robbins wouldn't like the irregular presentation of photos, but he did.

**Comment by cchristopherhowardd** [comment]
I get that Marsha Ginsberg's photo is super wide, but images of Samiya Bashir and Pamela Z essentially have a ratio of 600 x 400 pixels. This seems totally normal.

**Comment by cchristopherhowardd** [comment]
A related issue is that People photos on individual pages are all small and flush left. 

<img width="1386" alt="Screen Shot 2020-04-15 at 12 52 58 PM" src="https://user-images.githubusercontent.com/38765846/79366989-174d2e00-7f1b-11ea-8a94-8b1d250911e5.png">

<img width="1385" alt="Screen Shot 2020-04-15 at 1 15 14 PM" src="https://user-images.githubusercontent.com/38765846/79367048-2e8c1b80-7f1b-11ea-9be0-243bd2172bb1.png">

**Comment by jasloe** [comment]
I ambitiously tried to write one style to handle all images. Clearly, it's not working. Going to roll back to the old image handling configuration. :(
