### ISSUE TITLE
Lost formatting options for body sections 

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#292]
After the merge, the staging site lost formatting options for the body section of most pages that take this kind of content. We used to have a drop-down for headers, normal text, etc., and for making lists of bullets. Those are two that I remember using a lot. There were probably a couple other options that we've lost, too.

<img width="947" alt="Screen Shot 2020-04-28 at 10 08 24 AM" src="https://user-images.githubusercontent.com/38765846/80497542-9ccbd780-8938-11ea-91e6-0159535bf76c.png">

**Comment by jasloe** [comment]
Right. That was intentional and temporary. I was having a few problems with the editor which are resolved now. 

I've constrained the number of header tags available to h3 and h4 Here's a quick summary of how headers work:

h1: node title (about, news feature title, etc.)
h2: index title (on index page, link to about/mission, about/place; left column section titles on inner pages)
h3: headers in body content 
h4: headers in body content

**Comment by cchristopherhowardd** [comment]
Great, thanks.
