### ISSUE TITLE
Move Society of Fellows from People to About

### ISSUE THREAD

**Issue by cchristopherhowardd** [aarome/aarome#306]
The point person from the Society of Fellows feels that its section ( https://staging.aarome.org/society-of-fellows ) belongs on the About index page ( https://staging.aarome.org/about ) instead of the People page ( https://staging.aarome.org/people ), where it currently resides. Marques and I agree. Could you please move the rectangular box for Society of Fellows to About and place it after Rome Sustainable Food Project and before Tours? 

The SOF section should keep its URL of https://staging.aarome.org/society-of-fellows and not become https://staging.aarome.org/about/society-of-fellows.

**Comment by jasloe** [comment]
Pushed to staging, ready for testing. The only issue here is that 'About' in the main menu won't have an active state. This is because the active states depend on the path, that is 

/about/something –– 'About' displays as #f16541.
/something –– /about not in path and won't display as ##f16541.

I can use some Javascript to add the necessary class –– ```.is-active``` –– to the menu item, though postponing as it is a relatively low priority.
