### ISSUE TITLE
Portrait photos for Residents

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#72]
The graphic design specifies the inclusion of portraits for current Fellows, Residents, Italian Fellows, and Affiliated Fellows. 

We have portraits of current (and, for that matter, past Fellows through 2010-11). 

Italian Fellow portraits are so-so but usable. 

@cchristopherhowardd: We'll need portraits for Residents and Affiliated Fellows (when the fellowship recipient names are released).

**Comment by cchristopherhowardd** [comment]
Is my task to replace existing images with better-quality ones? 

Related question: should we create a graphic that will act as a placeholder for the hundreds (thousands?) of Fellows, Residents, and others from before 2010?

**Comment by jasloe** [comment]
Upshot is that there's enough information to minimally populate resident records, excepting images. I'll post what I have for ~300 fellows post-2010 to dev so you can see. Breaking that out into another ticket. 

I've posted the entire corpus of images in this tar file. 

https://aarome-backups.s3.amazonaws.com/aarome-org-image-archive.tar

The manifest is attached to this ticket. 

[manifest.txt](https://github.com/aarome/aarome/files/2470688/manifest.txt)

As far as I know, we have no canonical image resources for residents. Not sure why this part of the site was never fully built out, but there it is: https://www.aarome.org/people/current/residents

**Comment by cchristopherhowardd** [comment]
Regarding the Residents page ( https://www.aarome.org/people/current/residents ), the names were apparently replaced annually, without realizing that historical information is lost. Those folks will be added in due time.

**Comment by cchristopherhowardd** [comment]
I _can_ locate images from the last several years, as residents have been featured in _AAR Magazine_ since 2015. Those photos are lying around in ShareFile and elsewhere.

**Comment by jasloe** [comment]
Sweet. Let's take 5 minutes to look the share tomorrow. There may be some metadata that we can exploit to gather what we're after.

**Comment by cchristopherhowardd** [comment]
If you're working on a homepage for Mark Robbins's board presentation, you can drop these images into the Invited Residents section. Crop as necessary.
[Residents.zip](https://github.com/aarome/aarome/files/2566963/Residents.zip)

**Comment by cchristopherhowardd** [comment]
Is it possible to include a caption for photos of fellows, residents, and affiliated fellows? In some cases a photographer's credit/copyright line is needed.

**Comment by jasloe** [comment]
Sure no problem. Will add to all media types.

**Comment by cchristopherhowardd** [comment]
A current Italian Fellow, Carmen Belmonte (http://dev.aarome.org/people/italian-fellows/carmen-belmonte), is not showing up in the IF section (http://dev.aarome.org/people/italian-fellows).

**Comment by cchristopherhowardd** [comment]
Never mind--she is there now. I changed the dates of her fellowship to 01/01/18 to 01/01/19.

**Comment by cchristopherhowardd** [comment]
I can point out that the name of each IF's fellowship isn't appearing on their page. For instance, http://dev.aarome.org/people/italian-fellows/ila-b-ka does not list the name of his fellowship (Enel Italian Fellow in Architecture, Urban Design, and Landscape Architecture) even though the back end of his page contains this information.

Also, I changed his last name from Beka to Bêka, and the URL doesn't recognize the e anyone.

**Comment by jasloe** [comment]
No? Under Modern Italian Studies?

**Comment by jasloe** [comment]
> I can point out that the name of each IF's fellowship isn't appearing on their page. For instance, http://dev.aarome.org/people/italian-fellows/ila-b-ka does not list the name of his fellowship (Enel Italian Fellow in Architecture, Urban Design, and Landscape Architecture) even though the back end of his page contains this information.
> 
> Also, I changed his last name from Beka to Bêka, and the URL doesn't recognize the e anyone.

Ok, will take a look.

**Comment by jasloe** [comment]
> I can point out that the name of each IF's fellowship isn't appearing on their page. For instance, http://dev.aarome.org/people/italian-fellows/ila-b-ka does not list the name of his fellowship (Enel Italian Fellow in Architecture, Urban Design, and Landscape Architecture) even though the back end of his page contains this information.
> 
> Also, I changed his last name from Beka to Bêka, and the URL doesn't recognize the e anyone.

Ok, I added the IF name field to the view. 

Regarding non-ascii characters, I'll have to figure out a way to convert unicode to ascii for the purposes of URLs. Let me think about that a little bit.

**Comment by jasloe** [comment]
> > I can point out that the name of each IF's fellowship isn't appearing on their page. For instance, http://dev.aarome.org/people/italian-fellows/ila-b-ka does not list the name of his fellowship (Enel Italian Fellow in Architecture, Urban Design, and Landscape Architecture) even though the back end of his page contains this information.
> > Also, I changed his last name from Beka to Bêka, and the URL doesn't recognize the e anyone.
> 
> Ok, I added the IF name field to the view.
> 
> Regarding non-ascii characters, I'll have to figure out a way to convert unicode to ascii for the purposes of URLs. Let me think about that a little bit.

Ack, nevermind. Took me 2 minutes to figure it out.

**Comment by cchristopherhowardd** [comment]
Yesterday I was creating and updating People pages for Italian Fellows and Residents. I discovered that the template for Rome Prize Fellows and Italian Fellows doesn't work with Residents. I'll use http://dev.aarome.org/people/residents/marlon-blackwell as an example. 

1. Blackwell does not have a fellowship name, but he does have a residency name: William A. Bernoudy Architect in Residence. Can the page say "Residency" instead of "Fellowship"?

2. Residents rarely have project names. Can we hide the "Project" header?

3. Residents don't have "Project Descriptions" but rather we write short biographical entries with quotes from the residents. Can we call this header "Biography"? 

4. A general concern regarding the "Profession(s)" field for People pages. A person often has multiple affiliations (academic, job/company) like Blackwell does. In order for the page to express these facts, I have to add the word "and" in the field for the second affiliation. Is it possible to list multiple affiliations on their own lines? This seems like a more coherent way to present the information.
<img width="904" alt="screen shot 2019-03-01 at 11 12 36 am" src="https://user-images.githubusercontent.com/38765846/53651258-3fdd7000-3c14-11e9-9e58-2758f8f61444.png">
<img width="630" alt="screen shot 2019-03-01 at 11 12 18 am" src="https://user-images.githubusercontent.com/38765846/53651270-45d35100-3c14-11e9-9897-47be0bb6a3ee.png">

**Comment by jasloe** [comment]
Sure, easy enough. Give me an hour to rattle that off.
