### ISSUE TITLE
Link to other nodes and entities from body copy

### ISSUE THREAD

**Issue by jasloe** [aarome/aarome#92]

**Comment by cchristopherhowardd** [comment]
Can we reopen this issue? I would like to know how links on AAR webpages to other AAR webpages will work on the new site. Can any changes be automated, or will we suffer from widespread link rot?

**Comment by jasloe** [comment]
I can build a "picker" that selects the page to which you want to link. Would that work?

**Comment by cchristopherhowardd** [comment]
I don't know what a picker is.

What I'm referring to are situations across the site that will begin producing link rot. This page (https://www.aarome.org/news/features/the-body-and-the-road-to-justice) links to other AAR pages, such as:

https://www.aarome.org/news/features/mary-beard-lecture-review
https://www.aarome.org/news/features/2018-jerome-lectures-on-the-natural-world-pagans-and-christians
https://www.aarome.org/news/features/paolo-gioli-anthropolaroid

While the first and thirds links have direct equivalents on the new site (https://dev.aarome.org/news/features/mary-beard-lecture-review and https://dev.aarome.org/news/features/paolo-gioli-anthropolaroid), this one doesn't: https://dev.aarome.org/news/features/2018-jerome-lectures-on-the-natural-world-pagans-and-christians. That's because we've taken out the articles and prepositions: https://dev.aarome.org/news/features/2018-jerome-lectures-natural-world-pagans-christians.

Link rot that may be more difficult to detect is any AAR webpage that links to, for a random example, this event (https://www.aarome.org/events/calendar/2018-4?mini=2018-4#item-1975139), will never find its way to the new page (https://dev.aarome.org/events/calendar/joseph-williams-mediterranean-trade-builder-s-repertoire-effects-high-commerce).

**Comment by jasloe** [comment]
Going forward, if you create a link in body copy and start typing, the picker will look up other content. You can select which node you want to link to. This will create a reliable binding between two pieces of content.

Not much can be done about the last use case since the urls are built with variables. Standard practice is intelligently redirect users to an error/did you mean? page.

**Comment by cchristopherhowardd** [comment]
I finally figured out how this works last month and started using it.
